version: '2'

services:
  app:
    image: eeacms/european.cache.registry
    container_name: ecr.app
    depends_on:
    - postgres
    env_file:
    - .secret
    volumes:
    - /etc/localtime:/etc/localtime:ro

  postgres:
    image: postgres:9
    container_name: ecr.db
    environment:
    - POSTGRES_PASSWORD=ecr
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - data:/var/lib/postgresql/data
    - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  data:
    driver: local
