version: '2'

services:
  app:
    build:
      context: .
      args:
        REQFILE: requirements-dev.txt
    ports:
    - "5000"
    volumes:
    - .:/var/local/european.cache.registry

  postgres:
    image: postgres:9-alpine
    ports:
      - "5432:5432"
